config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  # Streamers
  resources :streamers

end

app/models/streamer.rb
class Streamer < ActiveRecord::Base

  extend FriendlyId
  friendly_id :league_ign

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/streamers_controller.rb
class StreamersController < ApplicationController
  before_action :set_streamer, only: [:show, :edit, :update, :destroy]

  # GET /streamers
  # GET /streamers.json
  def index
    @streamers = Streamer.all
  end

  # GET /streamers/1
  # GET /streamers/1.json
  def show
  end

  # GET /streamers/new
  def new
    @streamer = Streamer.new
  end

  # GET /streamers/1/edit
  def edit
  end

  # POST /streamers
  # POST /streamers.json
  def create
    @streamer = Streamer.new(streamer_params)

    respond_to do |format|
      if @streamer.save
        format.html { redirect_to @streamer, notice: 'Streamer was successfully created.' }
        format.json { render :show, status: :created, location: @streamer }
      else
        format.html { render :new }
        format.json { render json: @streamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streamers/1
  # PATCH/PUT /streamers/1.json
  def update
    respond_to do |format|
      if @streamer.update(streamer_params)
        format.html { redirect_to @streamer, notice: 'Streamer was successfully updated.' }
        format.json { render :show, status: :ok, location: @streamer }
      else
        format.html { render :edit }
        format.json { render json: @streamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streamers/1
  # DELETE /streamers/1.json
  def destroy
    @streamer.destroy
    respond_to do |format|
      format.html { redirect_to streamers_url, notice: 'Streamer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_streamer
      @streamer = Streamer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def streamer_params
      params.require(:streamer).permit(:twitch_username, :league_ign, :name, :server, :division, :tier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/streamers_helper.rb
module StreamersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaguepd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/streamers/_form.html.erb
<%= form_for(@streamer) do |f| %>
  <% if @streamer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@streamer.errors.count, "error") %> prohibited this streamer from being saved:</h2>

      <ul>
      <% @streamer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :twitch_username %><br>
    <%= f.text_field :twitch_username %>
  </div>
  <div class="field">
    <%= f.label :league_ign %><br>
    <%= f.text_field :league_ign %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :server %><br>
    <%= f.text_field :server %>
  </div>
  <div class="field">
    <%= f.label :division %><br>
    <%= f.text_field :division %>
  </div>
  <div class="field">
    <%= f.label :tier %><br>
    <%= f.text_field :tier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/streamers/edit.html.erb
<h1>Editing Streamer</h1>

<%= render 'form' %>

<%= link_to 'Show', @streamer %> |
<%= link_to 'Back', streamers_path %>

app/views/streamers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Streamers</h1>

<table>
  <thead>
    <tr>
      <th>Twitch username</th>
      <th>League ign</th>
      <th>Name</th>
      <th>Server</th>
      <th>Division</th>
      <th>Tier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @streamers.each do |streamer| %>
      <tr>
        <td><%= streamer.twitch_username %></td>
        <td><%= streamer.league_ign %></td>
        <td><%= streamer.name %></td>
        <td><%= streamer.server %></td>
        <td><%= streamer.division %></td>
        <td><%= streamer.tier %></td>
        <td><%= link_to 'Show', streamer %></td>
        <td><%= link_to 'Edit', edit_streamer_path(streamer) %></td>
        <td><%= link_to 'Destroy', streamer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Streamer', new_streamer_path %>

app/views/streamers/new.html.erb
<h1>New Streamer</h1>

<%= render 'form' %>

<%= link_to 'Back', streamers_path %>

app/views/streamers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twitch username:</strong>
  <%= @streamer.twitch_username %>
</p>

<p>
  <strong>League ign:</strong>
  <%= @streamer.league_ign %>
</p>

<p>
  <strong>Name:</strong>
  <%= @streamer.name %>
</p>

<p>
  <strong>Server:</strong>
  <%= @streamer.server %>
</p>

<p>
  <strong>Division:</strong>
  <%= @streamer.division %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @streamer.tier %>
</p>

<%= link_to 'Edit', edit_streamer_path(@streamer) %> |
<%= link_to 'Back', streamers_path %>